# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-cors-corsrule.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Resources:
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
    # Set CORS
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD # returns metadata for an object without the object itself
            MaxAge: 3000 # seconds to keep cache of preflight response

Outputs:
  AttachmentBucketName:
    Value:
      Ref: AttachmentsBucket